version: '3.8'

services:
  opsflow-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENV=development
      - DEBUG=true
      - DATABASE_URL=sqlite:///./opsflow.db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-here
      - PORTIA_API_KEY=your-portia-key
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Uncomment for PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: opsflow
  #     POSTGRES_USER: opsflow
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
